# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usermanagement.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='usermanagement.proto',
  package='usermanagement',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14usermanagement.proto\x12\x0eusermanagement\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd2\x02\n\x12registraionRequest\x12\x16\n\x0eregistrationId\x18\x01 \x01(\t\x12\x39\n\x15registrationtimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x39\n\x15lastUpdationtimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12*\n\x08\x66\x61\x63\x65\x62ook\x18\x05 \x01(\x0b\x32\x18.usermanagement.Facebook\x12*\n\x08linkedIn\x18\x06 \x01(\x0b\x32\x18.usermanagement.LinkedIn\x12(\n\x07twitter\x18\x07 \x01(\x0b\x32\x17.usermanagement.Twitter\x12,\n\tinstagram\x18\x08 \x01(\x0b\x32\x19.usermanagement.Instagram\")\n\x13registraionResponce\x12\x12\n\nresponceId\x18\x01 \x01(\t\"!\n\x0fuserInfoRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\"$\n\x10userInfoResponce\x12\x10\n\x08userData\x18\x01 \x01(\t\"\x15\n\x13notificationRequest\"\x16\n\x14notificationResponce\"\x11\n\x0fsettingsRequest\"\x12\n\x10settingsResponce\"/\n\x08\x46\x61\x63\x65\x62ook\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\r\n\x05\x61ppId\x18\x02 \x01(\t\"\n\n\x08LinkedIn\"\t\n\x07Twitter\"/\n\tInstagram\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x01 \x01(\t\x12\r\n\x05\x61ppId\x18\x02 \x01(\t2\xf3\x02\n\x14oculusUserManagement\x12U\n\x08register\x12\".usermanagement.registraionRequest\x1a#.usermanagement.registraionResponce\"\x00\x12N\n\x07getUser\x12\x1f.usermanagement.userInfoRequest\x1a .usermanagement.userInfoResponce\"\x00\x12V\n\x0f\x61\x63\x63ountSettings\x12\x1f.usermanagement.settingsRequest\x1a .usermanagement.settingsResponce\"\x00\x12\\\n\rnotifications\x12#.usermanagement.notificationRequest\x1a$.usermanagement.notificationResponce\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_REGISTRAIONREQUEST = _descriptor.Descriptor(
  name='registraionRequest',
  full_name='usermanagement.registraionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='registrationId', full_name='usermanagement.registraionRequest.registrationId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='registrationtimestamp', full_name='usermanagement.registraionRequest.registrationtimestamp', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastUpdationtimestamp', full_name='usermanagement.registraionRequest.lastUpdationtimestamp', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='facebook', full_name='usermanagement.registraionRequest.facebook', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='linkedIn', full_name='usermanagement.registraionRequest.linkedIn', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='twitter', full_name='usermanagement.registraionRequest.twitter', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instagram', full_name='usermanagement.registraionRequest.instagram', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=412,
)


_REGISTRAIONRESPONCE = _descriptor.Descriptor(
  name='registraionResponce',
  full_name='usermanagement.registraionResponce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='responceId', full_name='usermanagement.registraionResponce.responceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=455,
)


_USERINFOREQUEST = _descriptor.Descriptor(
  name='userInfoRequest',
  full_name='usermanagement.userInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='usermanagement.userInfoRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=490,
)


_USERINFORESPONCE = _descriptor.Descriptor(
  name='userInfoResponce',
  full_name='usermanagement.userInfoResponce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userData', full_name='usermanagement.userInfoResponce.userData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=528,
)


_NOTIFICATIONREQUEST = _descriptor.Descriptor(
  name='notificationRequest',
  full_name='usermanagement.notificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=551,
)


_NOTIFICATIONRESPONCE = _descriptor.Descriptor(
  name='notificationResponce',
  full_name='usermanagement.notificationResponce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=575,
)


_SETTINGSREQUEST = _descriptor.Descriptor(
  name='settingsRequest',
  full_name='usermanagement.settingsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=577,
  serialized_end=594,
)


_SETTINGSRESPONCE = _descriptor.Descriptor(
  name='settingsResponce',
  full_name='usermanagement.settingsResponce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=596,
  serialized_end=614,
)


_FACEBOOK = _descriptor.Descriptor(
  name='Facebook',
  full_name='usermanagement.Facebook',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='access_token', full_name='usermanagement.Facebook.access_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='appId', full_name='usermanagement.Facebook.appId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=616,
  serialized_end=663,
)


_LINKEDIN = _descriptor.Descriptor(
  name='LinkedIn',
  full_name='usermanagement.LinkedIn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=665,
  serialized_end=675,
)


_TWITTER = _descriptor.Descriptor(
  name='Twitter',
  full_name='usermanagement.Twitter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=677,
  serialized_end=686,
)


_INSTAGRAM = _descriptor.Descriptor(
  name='Instagram',
  full_name='usermanagement.Instagram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accessToken', full_name='usermanagement.Instagram.accessToken', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='appId', full_name='usermanagement.Instagram.appId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=688,
  serialized_end=735,
)

_REGISTRAIONREQUEST.fields_by_name['registrationtimestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_REGISTRAIONREQUEST.fields_by_name['lastUpdationtimestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_REGISTRAIONREQUEST.fields_by_name['facebook'].message_type = _FACEBOOK
_REGISTRAIONREQUEST.fields_by_name['linkedIn'].message_type = _LINKEDIN
_REGISTRAIONREQUEST.fields_by_name['twitter'].message_type = _TWITTER
_REGISTRAIONREQUEST.fields_by_name['instagram'].message_type = _INSTAGRAM
DESCRIPTOR.message_types_by_name['registraionRequest'] = _REGISTRAIONREQUEST
DESCRIPTOR.message_types_by_name['registraionResponce'] = _REGISTRAIONRESPONCE
DESCRIPTOR.message_types_by_name['userInfoRequest'] = _USERINFOREQUEST
DESCRIPTOR.message_types_by_name['userInfoResponce'] = _USERINFORESPONCE
DESCRIPTOR.message_types_by_name['notificationRequest'] = _NOTIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['notificationResponce'] = _NOTIFICATIONRESPONCE
DESCRIPTOR.message_types_by_name['settingsRequest'] = _SETTINGSREQUEST
DESCRIPTOR.message_types_by_name['settingsResponce'] = _SETTINGSRESPONCE
DESCRIPTOR.message_types_by_name['Facebook'] = _FACEBOOK
DESCRIPTOR.message_types_by_name['LinkedIn'] = _LINKEDIN
DESCRIPTOR.message_types_by_name['Twitter'] = _TWITTER
DESCRIPTOR.message_types_by_name['Instagram'] = _INSTAGRAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

registraionRequest = _reflection.GeneratedProtocolMessageType('registraionRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRAIONREQUEST,
  '__module__' : 'usermanagement_pb2'
  # @@protoc_insertion_point(class_scope:usermanagement.registraionRequest)
  })
_sym_db.RegisterMessage(registraionRequest)

registraionResponce = _reflection.GeneratedProtocolMessageType('registraionResponce', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRAIONRESPONCE,
  '__module__' : 'usermanagement_pb2'
  # @@protoc_insertion_point(class_scope:usermanagement.registraionResponce)
  })
_sym_db.RegisterMessage(registraionResponce)

userInfoRequest = _reflection.GeneratedProtocolMessageType('userInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERINFOREQUEST,
  '__module__' : 'usermanagement_pb2'
  # @@protoc_insertion_point(class_scope:usermanagement.userInfoRequest)
  })
_sym_db.RegisterMessage(userInfoRequest)

userInfoResponce = _reflection.GeneratedProtocolMessageType('userInfoResponce', (_message.Message,), {
  'DESCRIPTOR' : _USERINFORESPONCE,
  '__module__' : 'usermanagement_pb2'
  # @@protoc_insertion_point(class_scope:usermanagement.userInfoResponce)
  })
_sym_db.RegisterMessage(userInfoResponce)

notificationRequest = _reflection.GeneratedProtocolMessageType('notificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONREQUEST,
  '__module__' : 'usermanagement_pb2'
  # @@protoc_insertion_point(class_scope:usermanagement.notificationRequest)
  })
_sym_db.RegisterMessage(notificationRequest)

notificationResponce = _reflection.GeneratedProtocolMessageType('notificationResponce', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONRESPONCE,
  '__module__' : 'usermanagement_pb2'
  # @@protoc_insertion_point(class_scope:usermanagement.notificationResponce)
  })
_sym_db.RegisterMessage(notificationResponce)

settingsRequest = _reflection.GeneratedProtocolMessageType('settingsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETTINGSREQUEST,
  '__module__' : 'usermanagement_pb2'
  # @@protoc_insertion_point(class_scope:usermanagement.settingsRequest)
  })
_sym_db.RegisterMessage(settingsRequest)

settingsResponce = _reflection.GeneratedProtocolMessageType('settingsResponce', (_message.Message,), {
  'DESCRIPTOR' : _SETTINGSRESPONCE,
  '__module__' : 'usermanagement_pb2'
  # @@protoc_insertion_point(class_scope:usermanagement.settingsResponce)
  })
_sym_db.RegisterMessage(settingsResponce)

Facebook = _reflection.GeneratedProtocolMessageType('Facebook', (_message.Message,), {
  'DESCRIPTOR' : _FACEBOOK,
  '__module__' : 'usermanagement_pb2'
  # @@protoc_insertion_point(class_scope:usermanagement.Facebook)
  })
_sym_db.RegisterMessage(Facebook)

LinkedIn = _reflection.GeneratedProtocolMessageType('LinkedIn', (_message.Message,), {
  'DESCRIPTOR' : _LINKEDIN,
  '__module__' : 'usermanagement_pb2'
  # @@protoc_insertion_point(class_scope:usermanagement.LinkedIn)
  })
_sym_db.RegisterMessage(LinkedIn)

Twitter = _reflection.GeneratedProtocolMessageType('Twitter', (_message.Message,), {
  'DESCRIPTOR' : _TWITTER,
  '__module__' : 'usermanagement_pb2'
  # @@protoc_insertion_point(class_scope:usermanagement.Twitter)
  })
_sym_db.RegisterMessage(Twitter)

Instagram = _reflection.GeneratedProtocolMessageType('Instagram', (_message.Message,), {
  'DESCRIPTOR' : _INSTAGRAM,
  '__module__' : 'usermanagement_pb2'
  # @@protoc_insertion_point(class_scope:usermanagement.Instagram)
  })
_sym_db.RegisterMessage(Instagram)



_OCULUSUSERMANAGEMENT = _descriptor.ServiceDescriptor(
  name='oculusUserManagement',
  full_name='usermanagement.oculusUserManagement',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=738,
  serialized_end=1109,
  methods=[
  _descriptor.MethodDescriptor(
    name='register',
    full_name='usermanagement.oculusUserManagement.register',
    index=0,
    containing_service=None,
    input_type=_REGISTRAIONREQUEST,
    output_type=_REGISTRAIONRESPONCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getUser',
    full_name='usermanagement.oculusUserManagement.getUser',
    index=1,
    containing_service=None,
    input_type=_USERINFOREQUEST,
    output_type=_USERINFORESPONCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='accountSettings',
    full_name='usermanagement.oculusUserManagement.accountSettings',
    index=2,
    containing_service=None,
    input_type=_SETTINGSREQUEST,
    output_type=_SETTINGSRESPONCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='notifications',
    full_name='usermanagement.oculusUserManagement.notifications',
    index=3,
    containing_service=None,
    input_type=_NOTIFICATIONREQUEST,
    output_type=_NOTIFICATIONRESPONCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OCULUSUSERMANAGEMENT)

DESCRIPTOR.services_by_name['oculusUserManagement'] = _OCULUSUSERMANAGEMENT

# @@protoc_insertion_point(module_scope)
