# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protobufs.nlpengine_pb2 as nlpengine__pb2


class NLPEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Summary = channel.unary_unary(
                '/nlpengine.NLPEngine/Summary',
                request_serializer=nlpengine__pb2.RequestMessage.SerializeToString,
                response_deserializer=nlpengine__pb2.ResponseMessage.FromString,
                )
        self.TextAnalytics = channel.unary_unary(
                '/nlpengine.NLPEngine/TextAnalytics',
                request_serializer=nlpengine__pb2.RequestMessage.SerializeToString,
                response_deserializer=nlpengine__pb2.ResponseMessage.FromString,
                )
        self.Sentiment = channel.unary_unary(
                '/nlpengine.NLPEngine/Sentiment',
                request_serializer=nlpengine__pb2.RequestMessage.SerializeToString,
                response_deserializer=nlpengine__pb2.ResponseMessage.FromString,
                )
        self.getProfanity = channel.unary_unary(
                '/nlpengine.NLPEngine/getProfanity',
                request_serializer=nlpengine__pb2.RequestMessage.SerializeToString,
                response_deserializer=nlpengine__pb2.ResponseMessage.FromString,
                )


class NLPEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Summary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TextAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sentiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getProfanity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NLPEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Summary': grpc.unary_unary_rpc_method_handler(
                    servicer.Summary,
                    request_deserializer=nlpengine__pb2.RequestMessage.FromString,
                    response_serializer=nlpengine__pb2.ResponseMessage.SerializeToString,
            ),
            'TextAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.TextAnalytics,
                    request_deserializer=nlpengine__pb2.RequestMessage.FromString,
                    response_serializer=nlpengine__pb2.ResponseMessage.SerializeToString,
            ),
            'Sentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.Sentiment,
                    request_deserializer=nlpengine__pb2.RequestMessage.FromString,
                    response_serializer=nlpengine__pb2.ResponseMessage.SerializeToString,
            ),
            'getProfanity': grpc.unary_unary_rpc_method_handler(
                    servicer.getProfanity,
                    request_deserializer=nlpengine__pb2.RequestMessage.FromString,
                    response_serializer=nlpengine__pb2.ResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nlpengine.NLPEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NLPEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Summary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nlpengine.NLPEngine/Summary',
            nlpengine__pb2.RequestMessage.SerializeToString,
            nlpengine__pb2.ResponseMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TextAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nlpengine.NLPEngine/TextAnalytics',
            nlpengine__pb2.RequestMessage.SerializeToString,
            nlpengine__pb2.ResponseMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nlpengine.NLPEngine/Sentiment',
            nlpengine__pb2.RequestMessage.SerializeToString,
            nlpengine__pb2.ResponseMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getProfanity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nlpengine.NLPEngine/getProfanity',
            nlpengine__pb2.RequestMessage.SerializeToString,
            nlpengine__pb2.ResponseMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
