# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oculus_analytics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='oculus_analytics.proto',
  package='oculus_analytics',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16oculus_analytics.proto\x12\x10oculus_analytics\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n\x0fuserPostRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06pageId\x18\x02 \x01(\t\x12\x16\n\x0eregistrationId\x18\x03 \x01(\t\"F\n\x0cuserResponce\x12\x1b\n\x13processedReportData\x18\x01 \x01(\t\x12\x19\n\x11processedReportId\x18\x02 \x01(\t2\xd0\x03\n\x0foculusAnalytics\x12T\n\rpostAnalytics\x12!.oculus_analytics.userPostRequest\x1a\x1e.oculus_analytics.userResponce\"\x00\x12T\n\ruserAnalytics\x12!.oculus_analytics.userPostRequest\x1a\x1e.oculus_analytics.userResponce\"\x00\x12U\n\x0etrendAnalytics\x12!.oculus_analytics.userPostRequest\x1a\x1e.oculus_analytics.userResponce\"\x00\x12]\n\x16socialNetworkAnalytics\x12!.oculus_analytics.userPostRequest\x1a\x1e.oculus_analytics.userResponce\"\x00\x12[\n\x14\x61udienceSegmentation\x12!.oculus_analytics.userPostRequest\x1a\x1e.oculus_analytics.userResponce\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_USERPOSTREQUEST = _descriptor.Descriptor(
  name='userPostRequest',
  full_name='oculus_analytics.userPostRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='oculus_analytics.userPostRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageId', full_name='oculus_analytics.userPostRequest.pageId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='registrationId', full_name='oculus_analytics.userPostRequest.registrationId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=146,
)


_USERRESPONCE = _descriptor.Descriptor(
  name='userResponce',
  full_name='oculus_analytics.userResponce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='processedReportData', full_name='oculus_analytics.userResponce.processedReportData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processedReportId', full_name='oculus_analytics.userResponce.processedReportId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=218,
)

DESCRIPTOR.message_types_by_name['userPostRequest'] = _USERPOSTREQUEST
DESCRIPTOR.message_types_by_name['userResponce'] = _USERRESPONCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

userPostRequest = _reflection.GeneratedProtocolMessageType('userPostRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERPOSTREQUEST,
  '__module__' : 'oculus_analytics_pb2'
  # @@protoc_insertion_point(class_scope:oculus_analytics.userPostRequest)
  })
_sym_db.RegisterMessage(userPostRequest)

userResponce = _reflection.GeneratedProtocolMessageType('userResponce', (_message.Message,), {
  'DESCRIPTOR' : _USERRESPONCE,
  '__module__' : 'oculus_analytics_pb2'
  # @@protoc_insertion_point(class_scope:oculus_analytics.userResponce)
  })
_sym_db.RegisterMessage(userResponce)



_OCULUSANALYTICS = _descriptor.ServiceDescriptor(
  name='oculusAnalytics',
  full_name='oculus_analytics.oculusAnalytics',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=221,
  serialized_end=685,
  methods=[
  _descriptor.MethodDescriptor(
    name='postAnalytics',
    full_name='oculus_analytics.oculusAnalytics.postAnalytics',
    index=0,
    containing_service=None,
    input_type=_USERPOSTREQUEST,
    output_type=_USERRESPONCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='userAnalytics',
    full_name='oculus_analytics.oculusAnalytics.userAnalytics',
    index=1,
    containing_service=None,
    input_type=_USERPOSTREQUEST,
    output_type=_USERRESPONCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='trendAnalytics',
    full_name='oculus_analytics.oculusAnalytics.trendAnalytics',
    index=2,
    containing_service=None,
    input_type=_USERPOSTREQUEST,
    output_type=_USERRESPONCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='socialNetworkAnalytics',
    full_name='oculus_analytics.oculusAnalytics.socialNetworkAnalytics',
    index=3,
    containing_service=None,
    input_type=_USERPOSTREQUEST,
    output_type=_USERRESPONCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='audienceSegmentation',
    full_name='oculus_analytics.oculusAnalytics.audienceSegmentation',
    index=4,
    containing_service=None,
    input_type=_USERPOSTREQUEST,
    output_type=_USERRESPONCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OCULUSANALYTICS)

DESCRIPTOR.services_by_name['oculusAnalytics'] = _OCULUSANALYTICS

# @@protoc_insertion_point(module_scope)
